stages:
  - test
  - build
  - deploy

test-js:
  image: node:6
  stage: test
  script:
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list
    - apt-get update && apt-get install --no-install-recommends -y google-chrome-stable
    - npm install
    - npm install -g karma-cli
    - karma start --single-run
  allow_failure: false


build:
  image: python:2.7
  stage: build
  script:
    - python --version
    - pip install virtualenv
    - virtualenv env --no-site-packages
    - source env/bin/activate
    - pip install -r requirements.txt
  allow_failure: false

build-n-deploy:
  image: docker
  stage: deploy
  dependencies:
      - build
  services:
    - docker:dind
  script:
    - apk -v --update add python py-pip && pip install --upgrade awscli
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t 111633362669.dkr.ecr.us-east-1.amazonaws.com/nysa-api-server:${CI_COMMIT_SHA:0:8} .
    - docker push 111633362669.dkr.ecr.us-east-1.amazonaws.com/nysa-api-server:${CI_COMMIT_SHA:0:8}
  allow_failure: false